# Generated by Django 2.1.5 on 2019-01-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('birth_year', models.IntegerField(default='2019')),
                ('birth_month', models.IntegerField(default='01')),
                ('birth_day', models.IntegerField(default='15')),
            ],
        ),
    ]
