# Generated by Django 2.1.5 on 2019-01-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peeps_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='LastName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='firstName',
            new_name='last_name',
        ),
    ]
